---
- hosts: all
  become: yes

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    #- name: Check if Drupal is already set up.
    #  stat: "path={{ drupal_core_path }}/index.php"
    #  register: drupal_site
    #  ignore_errors: true

    #- name: Define drupal_site_exists
    #  set_fact:
    #    drupal_site_exists: "{{ drupal_site.stat.exists|default(false) }}"

    - include: tasks/sshd.yml
    - include: tasks/www.yml
    - include: tasks/apparmor.yml
      when: ansible_os_family == 'Debian'

    # Install site if configured.
    #- include: tasks/install-site.yml
    #  when: install_site
