---
- src: geerlingguy.apache
  version: 1.7.2
- src: geerlingguy.apache-php-fpm
  version: 1.0.2
- src: geerlingguy.composer
  version: 1.4.0
- src: geerlingguy.drush
  version: 1.1.3
- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.php
  version: 3.2.1
- src: geerlingguy.php-mysql
  version: 2.0.0
- src: geerlingguy.php-pecl
  version: 1.2.1
- src: geerlingguy.mysql
  version: 2.2.3
